train_datasets:
  - name: "parambharat/tamil_asr_corpus"
    split: "train"
    input_fields:
      - "audio"
      - "sentence"

  - name: "parambharat/ucla_dataset"
    split: "train"
    input_fields:
      - "audio"
      - "sentence"


eval_datasets:
  - name: "parambharat/tamil_asr_corpus"
    split: "test"
    input_fields:
      - "audio"
      - "sentence"

preprocessing:
  text:
    remove_special_characters: True
    lowercase: True
    remove_punctuation: True
    remove_latin_characters: False


train_batch_size: 16
num_workers: 8
debug: False
result_path: "results"
exp_name: "w2v_bert"
sampling_rate: 16000
warmup_steps: 100
learning_rate: 5e-5
save_steps: 600
eval_steps: 300
logging_steps: 300
save_total_limit: 2
push_to_hub: False
gradient_checkpointing: True
train_epochs: 10
gradient_accumulation_steps: 2